select sorg_unit_sk                 
  ,par_bp_sk                    
  ,bp_sk                        
  ,pset_sk                      
  ,prd_grp_sk                   
  ,pat_brd_inatn_cald_dt_sk     
  ,src_crea_dt_sk               
  ,fol_up_cald_dt_sk            
  ,trtt_strt_cald_dt_sk         
  ,trtt_end_cald_dt_sk          
  ,plan_devy_cald_dt_sk         
  ,bp_prd_rx_id                 
  ,bus_unit_cd                  
  ,dst_cd                       
  ,dr_dcf_cd                    
  ,dr_seg_cd                    
  ,insn_cd                      
  ,insn_dcf_dsf_cd              
  ,insn_sls_chnl_cd             
  ,insn_tier_cd                 
  ,regn_cd                      
  ,rf_cd                        
  ,sls_wrkr_cd                  
  ,terr_cd                      
  ,bus_unit_lcl_lang_nm         
  ,bus_unit_nm                  
  ,dst_lcl_lang_nm              
  ,dst_nm                       
  ,dr_nm                        
  ,insn_nm                      
  ,insn_trgt_type_nm            
  ,prd_nm                       
  ,prd_grp_nm                   
  ,regn_lcl_lang_nm             
  ,regn_nm                      
  ,sls_wrkr_nm                  
  ,stg_of_dis_nm                
  ,terr_lcl_lang_nm             
  ,terr_nm                      
  ,age_txt                      
  ,amt_of_devy_dsg_txt          
  ,cmbn_medc_txt                
  ,cmplctns_txt                 
  ,efct_1st_ln_txt              
  ,efct_2nd_ln_txt              
  ,efct_3rd_ln_txt              
  ,efct_4th_ln_txt              
  ,gndr_txt                     
  --,hstgy_txt                    
  --,pd_l1_sta_txt                
  ,hcp_intn_txt                 
  ,high_risk_chrmsm_abnrml_txt  
  ,msi_test_time_txt            
  ,mtx_wkly_rx_cmb_use_txt      
  ,pat_sta_cmplctn_txt          
  ,pat_cnf_txt                  
  ,perd_1st_ln_txt              
  ,perd_2nd_ln_txt              
  ,perd_3rd_ln_txt              
  ,perd_4th_ln_txt              
  ,prev_dis_txt                 
 -- ,prev_trtt_regm_txt           
  ,regm_1st_ln_txt              
  ,regm_2nd_ln_txt              
  ,regm_3rd_ln_txt              
  ,regm_4th_ln_txt              
  ,rlps_type_txt                
  ,rx_ln_txt                    
  ,spctby_txt                   
  ,sntvy_pomalidomide_txt       
 -- ,ther_area_txt                
  ,trtt_expc_prd_txt            
  ,trtt_hist_pomalidomide_txt   
  ,trtt_ln_txt                  
  ,acpa_dsg_ds                  
  ,bio_mlcl_use_ds              
  ,diags_ds                     
  ,trtt_termn_reas_ds           
  ,wt_num                       
  ,dis_dur_ct                   
  ,mtx_wkly_rx_dose_ct          
  ,last_modf_ts                 
  ,trgt_ind                     
  ,dual_terr_flag    from jp3a_cdw.s_sorg_sls_wrkr_bp_prd_cald_dt_srvy_fol_up
  minus
  select sorg_unit_sk                 
  ,par_bp_sk                    
  ,bp_sk                        
  ,pset_sk                      
  ,prd_grp_sk                   
  ,pat_brd_inatn_cald_dt_sk     
  ,src_crea_dt_sk               
  ,fol_up_cald_dt_sk            
  ,trtt_strt_cald_dt_sk         
  ,trtt_end_cald_dt_sk          
  ,plan_devy_cald_dt_sk         
  ,bp_prd_rx_id                 
  ,bus_unit_cd                  
  ,dst_cd                       
  ,dr_dcf_cd                    
  ,dr_seg_cd                    
  ,insn_cd                      
  ,insn_dcf_dsf_cd              
  ,insn_sls_chnl_cd             
  ,insn_tier_cd                 
  ,regn_cd                      
  ,rf_cd                        
  ,sls_wrkr_cd                  
  ,terr_cd                      
  ,bus_unit_lcl_lang_nm         
  ,bus_unit_nm                  
  ,dst_lcl_lang_nm              
  ,dst_nm                       
  ,dr_nm                        
  ,insn_nm                      
  ,insn_trgt_type_nm            
  ,prd_nm                       
  ,prd_grp_nm                   
  ,regn_lcl_lang_nm             
  ,regn_nm                      
  ,sls_wrkr_nm                  
  ,stg_of_dis_nm                
  ,terr_lcl_lang_nm             
  ,terr_nm                      
  ,age_txt                      
  ,amt_of_devy_dsg_txt          
  ,cmbn_medc_txt                
  ,cmplctns_txt                 
  ,efct_1st_ln_txt              
  ,efct_2nd_ln_txt              
  ,efct_3rd_ln_txt              
  ,efct_4th_ln_txt              
  ,gndr_txt                     
  --,hstgy_txt                    
  --,pd_l1_sta_txt                
  ,hcp_intn_txt                 
  ,high_risk_chrmsm_abnrml_txt  
  ,msi_test_time_txt            
  ,mtx_wkly_rx_cmb_use_txt      
  ,pat_sta_cmplctn_txt          
  ,pat_cnf_txt                  
  ,perd_1st_ln_txt              
  ,perd_2nd_ln_txt              
  ,perd_3rd_ln_txt              
  ,perd_4th_ln_txt              
  ,prev_dis_txt                 
 -- ,prev_trtt_regm_txt           
  ,regm_1st_ln_txt              
  ,regm_2nd_ln_txt              
  ,regm_3rd_ln_txt              
  ,regm_4th_ln_txt              
  ,rlps_type_txt                
  ,rx_ln_txt                    
  ,spctby_txt                   
  ,sntvy_pomalidomide_txt       
 -- ,ther_area_txt                
  ,trtt_expc_prd_txt            
  ,trtt_hist_pomalidomide_txt   
  ,trtt_ln_txt                  
  ,acpa_dsg_ds                  
  ,bio_mlcl_use_ds              
  ,diags_ds                     
  ,trtt_termn_reas_ds           
  ,wt_num                       
  ,dis_dur_ct                   
  ,mtx_wkly_rx_dose_ct          
  ,last_modf_ts                 
  ,trgt_ind                     
  ,dual_terr_flag     from jp_sandbox_ops.S_SORG_SLS_WRKR_BP_PRD_CALD_DT_SRVY_FOL_UP_1029 
  