CREATE TABLE jp2_int.dr_insn_actv_all_ntrgt_daily
(
   sorg_sk            integer,
   sls_wrkr_sk        integer,
   prd_sk             integer,
   cald_dt_sk         integer,
   dcf_dsf_cd         varchar(10),
   bp_par_sk          integer,
   par_bp_cd          varchar(20),
   par_bp_nm          varchar(300),
   trgt_type          varchar(20),
   chnl_type          varchar(200),
   tier               varchar(20),
   dr_id              varchar(10),
   bp_sk              integer,
   dr_cd			  varchar(255),
   dr_nm              varchar(300),
   trgt_flag          integer,
   dr_segn            varchar(50),
   terr_seq_num       integer,
   presn_p2p_cnt      integer,
   web_cnt            integer,
   approved_mail_cnt  integer,
   iva_cnt            integer,
   actual_detail_cnt  integer,
   covisit_cnt        integer,
   appnt_cnt          integer,
   exp_cnt            integer,
   trgt_cnt           integer
);


CREATE TABLE jp2_int.regn_dst_terr_mr_dr_insn_actv_daily
(
   regn_id            integer,
   regn_cd            varchar(50),
   regn_nm            varchar(200),
   dst_id             integer,
   dst_cd             varchar(50),
   dst_nm             varchar(200),
   terr_id            integer,
   terr_cd            varchar(50),
   terr_nm            varchar(200),
   mr_cd              varchar(50),
   mr_nm              varchar(200),
   sls_wrkr_sk        integer,
   prd_sk             integer,
   cald_dt_sk         integer,
   dcf_dsf_cd         varchar(10),
   bp_par_sk          integer,
   par_bp_cd          varchar(20),
   par_bp_nm          varchar(300),
   trgt_type          varchar(20),
   chnl_type          varchar(200),
   tier               varchar(20),
   dr_id              varchar(10),
   bp_sk              integer,
   dr_cd			  varchar(255),
   dr_nm              varchar(300),
   trgt_flag          integer,
   dr_segn            varchar(50),
   sls_wrkr_seq_num   integer,
   presn_p2p_cnt      integer,
   web_cnt            integer,
   approved_mail_cnt  integer,
   iva_cnt            integer,
   actual_detail_cnt  integer,
   covisit_cnt        integer,
   appnt_cnt          integer,
   exp_cnt            integer,
   trgt_cnt           integer
);

CREATE TABLE jp2_int.rpt_sorg_prd_dr_insn_all_atvy_daily
(
   regn_id             integer,
   regn_cd             varchar(50),
   regn_nm             varchar(200),
   dst_id              integer,
   dst_cd              varchar(50),
   dst_nm              varchar(200),
   terr_id             integer,
   terr_cd             varchar(50),
   terr_nm             varchar(200),
   mr_cd               varchar(50),
   mr_nm               varchar(200),
   dcf_dsf_cd          varchar(30),
   bp_par_sk           integer,
   bms_cd              varchar(30),
   insn_nm             varchar(300),
   trgt_type_cd        varchar(30),
   sls_chnl_cd         varchar(200),
   prd_shrt_ds         varchar(50),
   tier_cd             varchar(200),
   cald_dt_sk          integer,
   yr_sem_nbr          varchar(30),
   data_lvl_ds         varchar(20),
   dr_id               varchar(50),
   bp_sk               integer,
   dr_cd 				varchar(255),
   dr_nm               varchar(200),
   trgt_dr_flag        varchar(50),
   dr_seg_cd           varchar(50),
   plan_dtl_cnt        integer,
   actl_dtl_cnt        integer,
   app_dtl_cnt         integer,
   iva_dtl_cnt         integer,
   co_vst_dtl_cnt      integer,
   expl_mtg_dtl_cnt    integer,
   web_semr_dtl_cnt    integer,
   pp_dtl_cnt          integer,
   open_email_dtl_cnt  integer,
   dual_terr_flag      integer
);


CREATE TABLE jp3a_cdw.RPT_INSN_DR_PRD_ALL_DAILY_ATVY
(
BP_PAR_SK				integer,
BP_SK					integer,
PSET_SK					integer,
CALD_DT_SK				integer,
INSN_CD					VARCHAR(100),
DR_CD					VARCHAR(100),
INSN_NM					VARCHAR(255),
DR_NM					VARCHAR(255),
PGRP_NM					VARCHAR(50),
ACTL_DTL_DAILY_CT		NUMERIC(18),
APNTT_DTL_DAILY_CT		NUMERIC(18),	
APV_EMAIL_SENT_DAILY_CT NUMERIC(18),
CO_VIST_DTL_DAILY_CT    NUMERIC(18),
EXPL_MTG_DTL_DAILY_CT   NUMERIC(18),
IVA_DTL_DALY_CT         NUMERIC(18),
P2P_DAILY_CT            NUMERIC(18),
WEB_SEMINAR_DAILY_CT    NUMERIC(18),
CYCL_TIME_ID			INTEGER,
SCEN_ID					INTEGER,
INRT_TS					TIMESTAMP,
INRT_BY_NM				VARCHAR(50),
MODF_TS					TIMESTAMP,
MODF_BY_NM				VARCHAR(50)
);

CREATE TABLE jp_rpt_a.RPT_INSN_DR_PRD_ALL_DAILY_ATVY
(
BP_PAR_SK				integer,
BP_SK					integer,
PSET_SK					integer,
CALD_DT_SK				integer,
INSN_CD					VARCHAR(100),
DR_CD					VARCHAR(100),
INSN_NM					VARCHAR(255),
DR_NM					VARCHAR(255),
PGRP_NM					VARCHAR(50),
ACTL_DTL_DAILY_CT		NUMERIC(18),
APNTT_DTL_DAILY_CT		NUMERIC(18),	
APV_EMAIL_SENT_DAILY_CT NUMERIC(18),
CO_VIST_DTL_DAILY_CT    NUMERIC(18),
EXPL_MTG_DTL_DAILY_CT   NUMERIC(18),
IVA_DTL_DALY_CT         NUMERIC(18),
P2P_DAILY_CT            NUMERIC(18),
WEB_SEMINAR_DAILY_CT    NUMERIC(18),
CYCL_TIME_ID			INTEGER,
SCEN_ID					INTEGER,
INRT_TS					TIMESTAMP,
INRT_BY_NM				VARCHAR(50),
MODF_TS					TIMESTAMP,
MODF_BY_NM				VARCHAR(50),
snp_id					integer
);

